# Generated by Django 5.1.7 on 2025-04-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='infoText',
            field=models.CharField(max_length=20),
        ),
    ]
